default:

  # URL for getting project data
  # ef_pubxls_url: "https://dotaceeu.cz/getmedia/009dba87-d944-4f66-9bd4-2eb166e2ef92/2021_07_30_Seznam-operaci-_-List-of-operations.xls.aspx?ext=.xls"
  ef_pubxls_url: "https://dotaceeu.cz/getmedia/6297d56b-0b57-418d-ad25-dd16bd687479/2021_06-Seznam-operaci-_-List-of-operations.xls.aspx?ext=.xls"

  # PRV data-input

  agri_opendata_zipxml: ["agri_prijemci_2017.zip", "agri_prijemci_2018.zip", "agri_prijemci_2019.zip", "agri_prijemci_2020.zip"]
  agri_opendata_urls: ["https://www.szif.cz/cs/CmDocument?rid=%2Fapa_anon%2Fcs%2Fdokumenty_ke_stazeni%2Fpkp%2Fspd%2Fopendata%2F1563197147275.zip", "https://www.szif.cz/cs/CmDocument?rid=%2Fapa_anon%2Fcs%2Fdokumenty_ke_stazeni%2Fpkp%2Fspd%2Fopendata%2F1563197121858.zip", "https://www.szif.cz/cs/CmDocument?rid=%2Fapa_anon%2Fcs%2Fdokumenty_ke_stazeni%2Fpkp%2Fspd%2Fopendata%2F1590753721920.zip", "https://www.szif.cz/cs/CmDocument?rid=%2Fapa_anon%2Fcs%2Fdokumenty_ke_stazeni%2Fpkp%2Fspd%2Fopendata%2F1622192829773.zip"]
  agri_opendata_dir: "data-input/opendata-szif"
  prv_data_path: "data-input/sestavy-prv_2020-12/PRV 2014-20 k XII. 2020.XLSX"

  # sestavy from MS
  sest_dir: "data-input/sestavy 20210528"
  sest_xlsx_prj: "E001 Identifikace projektu.xlsx"
  sest_xlsx_fin: "E003 Finance celkem.xlsx"
  sest_xlsx_zop: "E004 Žádosti o platbu.xlsx"
  sest_xlsx_obl: "E005 Kategorizace_oblast.xlsx"


  # Quest/Hermin categorisations
  priority_prv_xls: "data-input/Navrh - KATEGORIZACE - Operace PRV + priority.xlsx"

  # Climate categoristions

  ## From legislation
  reg_table_nonagri_xlsx: "data-input/regulation-tables/reg-table_1_climate-categories_nonagri.xlsx"
  reg_table_agri_xlsx: "data-input/regulation-tables/reg-table_1_climate-categories_agri.xlsx"
  reg_table_agri_sheetname: "cz_priorities"

  # IDs
  czso_pop_table_id: "130149"

  # export location - macro
  export_dir: "data-export/export_202110"

  export_all_ops_xlsx: "sum_tagged_all_ops.xlsx"
  export_all_ops_detail_xlsx: "sum_tagged_all_ops_detail.xlsx"
  export_prv_detail_xlsx: "sum_tagged_prv_detail.xlsx"
  export_nonagri_detail_xlsx: "sum_tagged_nonagri_detail.xlsx"
  export_nonagri_projekty_xlsx: "sum_tagged_nonagri_projekty.xlsx"
  export_agri_detail_xlsx: "sum_tagged_agri_detail.xlsx"

  export_all_ops_csv: "sum_tagged_all_ops.csv"
  export_all_ops_detail_csv: "sum_tagged_all_ops_detail.csv"
  export_prv_detail_csv: "sum_tagged_prv_detail.csv"
  export_nonagri_detail_csv: "sum_tagged_nonagri_detail.csv"
  export_nonagri_projekty_parquet: "sum_tagged_nonagri_projekty.parquet"
  export_agri_detail_csv: "sum_tagged_agri_detail.csv"

  export_xlsx_a: "sum_quarterly.xlsx"
  export_xlsx_q: "sum_annual.xlsx"
  export_csv_a: "sum_quarterly.csv"
  export_csv_q: "sum_annual.csv"

  export_tagging_xlsx: "site/export-tagging-all.xlsx"

  export_cdbk_sum: "codebook_sum.yaml"
  export_cdbk_prj: "codebook_prj.yaml"

  repo_remote: "https://github.com/cdeorgcz/esiftagging"
