---
title: "Záznam kroků a poznatků"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Změny 3. 3. 2022


- upraveny revidované tagy:
  - v OP PIK u SC 01.3.10.3.2 "Zvýšit energetickou účinnost podnikatelského sektoru" na 0,4 => výrazná změna výsledku, mj. OP PIK je v čistém vyjádření pozitivní - podle textové analýzy projektů jde hlavně o zateplení, částečně fotovoltaiku
  - v OP PPR u SC 07.2.13.2.3 "Rozvoj nízkoemisní mobility v oblasti městské dopravy v uličním provozu" na 1 - jsou tam jen projekty na nákup elektrobusů a trolejbusů (zatím neproplacené, ale reálné)
  - v OP D u SC 04.2.40.2.2 "Vytvoření podmínek pro širší využití vozidel na alternativní pohon na silniční síti" na 0,4 (plyn tam tvoří výraznou menšinu)
- Zapracováno dodatečné pravidlo pro tagování podle implementačního nařízení [215/2014](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32014R0215#d1e165-65-1), čl. 1, odst 1 a: " 	

> in relation to financial data reported against intervention field codes that have a coefficient of zero, where financial data is reported in the thematic objective dimension against codes 04 and 05 set out in Table 5 of Annex I to this Regulation, the data shall be weighted with a 40 % coefficient in terms of their contribution to climate change objectives."

Tím přibylo cca 5 mld. Kč. v kategorii 40 % a tedy 2 mld. v čistém přínosu podle oficiální metodologie.

Při manuálním tagování toto pravidlo ignorujeme - lze dodatečně vytáhnout specifické cíle, kterých se to týkalo, a ověřit zase ručně.

[Export dat na Githubu](https://github.com/cdeorgcz/esiftagging/commits/main/data-export/export_202203) odráží tyto změny.

## Změny k 28. 2. 2022

Provedena validace výpočtů => oprava celkového součtu v hlavním grafu (bez dopadu na vážený klimatický příspěvek)

## Změny k 26. 2. 2022

Přibyly [grafy součtů podle tagů a OP v metologii CDE](s_output.html) (> Všechny OP - CDE)

Přibyla [explorační vizualizace](s_output.html) textových popisů projektů OP PIK zaměřených na zvyšování energetické účinnosti podnikatelského sektoru. (Témata > Úspory ve firmách).

## Změny k 24. 2. 2022

Přibyl [náhled vzorku projektů](sample.html), které změnily tag mezi oficiální a CDE metodologií.

## Změny k 31. 1. 2022

Aktualizace celého postupu, abychom využívali nejnovější možná data a přitom minimalizovali nepřesnost. Funguje to teď následovně:

- včechna finanční data o projektech bereme z veřejně dostupné tabulky na https://dotaceeu.cz/cs/statistiky-a-analyzy/seznamy-prijemcu
- k tomu doplňujeme z [open dat](https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F66002222%2F4b59efc04aae0acd97761bf5b7330b87) informaci o specifickém cíli, kterou potřebujeme pro manuální retagging
- u projektů, kde máme rozpad na SC a oblasti intervence v neveřejné sestavě od MMR (která je ale starší), použijeme tyto rozpady, protože jsou přesnější
- pokud je nemáme, dělíme projekt rovnoměrně do všech SC a OI, které jsou u něj uvedeny

Veřejná data se aktualizují automaticky, tj. při každém spuštění se použijí nejnovější dostupná. Pokud by tato automatika selhala nebo by bylo třeba "zmrazit" data k nějakému datu, do parametru `ef_pubxls_url` v souboru `config.yml` lze vložit odkaz přímo na požadovaný veřejný seznam příjemců podle https://dotaceeu.cz/cs/statistiky-a-analyzy/seznamy-prijemcu.

## Změny k 9. 1. 2022

- vloženy upravené manuální tagy
- srovnávací ["sankey" graf - záložka "Srovnání tagů"](s_output.html)
- [textová analýza projektů v teplárenství - záložka "Témata"](s_output.html)

## Úpravy a doplnění 14. 10. 2021

- v [exportech](https://github.com/cdeorgcz/esiftagging/tree/main/data-export/export_202110) doplněno:
  - sloupec `fin_vyuct_verejne`
  - v exportech na úrovni projektů doplněny sloupce s IČO a názvem příjemce a s anotací projektu
  - odstraněn export na projektové úrovni v CSV, ponechán jen excel - CSV byl příliš velký pro export na Github. Alternativně můžu dodat např. Parquet pro zpracování v Pythonu a R.
- přepočteny součty v exportech - drobná oprava po validaci.

Zbývající (ne)dodělávky trackuji v [Issues na Githubu](https://github.com/cdeorgcz/esiftagging/issues).

## Update 30. 9. 2021

### Nové

- [interaktivní náhledy kategorií pro ruční tagging](s_listing.html)

### Hotovo

- načtení dat PRV z open dat
- napojení oficiálních klima kategorií na data o SZP/PRV - viz [náhled výstupu](s_output.html)


### Doplněno

- [dokumentace projektu](s_doc.html)

### In progress

- tabulkový export hlavních výstupů
- formální dokumentace výstupů (codebook)

### Otázky

- má být OP Z a OP VVV v kategorii "0 %" nebo "neznámé/nic"?

## Update 6. 9. 2021

### Hotovo

- sestavení projektu včetně přípravy na opakovatelný recept
- [Github profil CDE](https://github.com/cdeorgcz) + základní [web rozcestník](https://cdeoorgcz.github.io)
- základ [dokumentace projektu](https://cdeoorgcz.github.io/esiftagging)
- [načtení dat ESIF ze sestav MMR](s_output.html)
- [načtení dat PRV ze sestavy MMR](s_output.html)

### In progress

- načtení dat PRV z open dat
- [rešerše kategorizací pro ESI fondy mimo PRV + PRV](research.html)

### K potvrzení (praktikálie)

- název github profilu + název projektu
- jazyk dokumentace

### K rozhodnutí (koncepční)

- zdroj dat ESIF
- kategorizace ESIF pro klima semafor (viz [rešerši](research.html))
- zdroj dat PRV
- zahrnutí plošných opatření PRV (viz [rešerši](research.html))
- zdroj kategorizací pro semafor z dat PRV
- možnost mezinárodního srovnání (výhledově)
